# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2007-2017
  project: Context Manager
  version: 2.0
  release: 2.0.0
  latex_documents:
  - - Index
    - context.tex
    - Context Manager
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    expressions:
    - http://docs.typo3.org/typo3cms/extensions/expressions/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
